### ISSUE TITLE
Prefix and commands?

### ISSUE THREAD

**Issue by omnidotnet** [Samrux/Pac-Man-Bot#7]
I don't know how to manage the bot.
What's it's prefix? And the commands?
For example, if I wanna play UNO, what command do I execute?

**Comment by kasefuchs** [comment]
Default bot prefix is: `<`
[config ref](https://github.com/orchidalloy/Pac-Man-Bot/blob/1f720423932abc9b5558281a452efb891e8e8f30/src/BotConfig.cs#L27)

To see the list of all the bot commands, you can join the bot support server or compile and run your bot instance, then call the `<help` command anyway

I think I'm a little bit, but I helped you.
